### ISSUE TITLE
다른 라우팅 라이브러리를 사용할 수 있나요?

### ISSUE THREAD

**Issue by scarf005** [blueStragglr/wanted-pre-onboarding-3-FE-quest#24]
[리액트 라우터](https://reactrouter.com/)는 라우트가 타입 안전하지 않다는 문제점이 있습니다. 아래와 같은 라우팅 라이브러리들은 라우트와 파라미터도 타입 안전하다는 특징이 있는데, 혹시 `react-router-dom` 이 아닌 다른 라이브러리를 사용해도 괜찮을까요?

-   [TanStack Router](https://github.com/tanstack/router)
-   [Type Route](https://github.com/zilch/type-route)
-   [Chicane](https://github.com/swan-io/chicane)

**Comment by blueStragglr** [comment]
네! 필요에 따라 자유롭게 라이브러리를 선택하셔도 됩니다 !
